name: telewin

services:
  web-app:
    container_name: web-app_con
    restart: on-failure
    build:
      context: ./
      dockerfile: ./dockerb/Dockerfile
    entrypoint:
      - /bin/sh
      - -c
      - python3 manage.py collectstatic --no-input && gunicorn --config gunicorn-cfg.py web_app.wsgi
    depends_on:
      - web-db
    networks:
      - network_default
    profiles:
      - web-app
      - all
    volumes:
      - ./:/app
      - media:/app/media/
      - static:/app/staticfiles/
    ports:
      - '8000:8000'

  prometheus-app:
    image: prom/prometheus:latest
    container_name: prometheus_con
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./django.rules:/etc/prometheus/django.rules
      - prometheus_data:/prometheus
    profiles:
      - all
    networks:
      - network_default
    expose:
      - "9090"
    depends_on:
      - web-app

  promtail-app:
    image: grafana/promtail
    container_name: protmail_con
    networks:
      - network_default
    expose:
      - "9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail_config.yml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml
    privileged: true

  loki-app:
    image: grafana/loki
    networks:
      - network_default
    container_name: loki_con
    expose:
      - "3100"
    volumes:
      - ./grafana_loki.yml:/etc/loki/local-config.yaml

  grafana-app:
    image: grafana/grafana
    networks:
      - network_default

    container_name: grafana_con
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml

  celery-worker:
    restart: "on-failure"
    container_name: celery-worker_con
    build:
      context: ./
      dockerfile: ./dockerb/Dockerfile
    entrypoint: celery -A web_app worker -l INFO
    profiles:
      - all
    depends_on:
      - web-app
      - redis
    networks:
      - network_default
    volumes:
      - ./:/app
#
  celery-beat:
    restart: "on-failure"
    container_name: celery-beat_con
    build:
      context: ./
      dockerfile: ./dockerb/Dockerfile
    entrypoint: celery -A web_app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    profiles:
      - all
    depends_on:
      - web-app
      - redis
    networks:
      - network_default
    volumes:
      - ./:/app

  tg-bot:
    build:
      context: ../bot
      dockerfile: ./docker/Dockerfile
    container_name: tg-bot_con
    entrypoint: python main.py
    networks:
      - network_default
    profiles:
      - bot
      - all
    volumes:
      - ../bot:/bot
      - media:/media/
    ports:
      - "8001:8001"

  reverse-proxy:
    image: "nginx:alpine"
#    restart: unless-stopped
    container_name: reverse-proxy_con
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/localhost.conf:/etc/nginx/nginx.conf:ro
      - app_certificates:/app_certificates
      - /etc/localtime:/etc/localtime:ro
      - media:/media/
      - static:/static/
    networks:
      - network_default
    profiles:
      - reverse-proxy
      - all
    depends_on:
      - web-app
      - tg-bot
      - prometheus-app

  web-db:
    image: postgres:17-alpine
    container_name: web-db_con
    restart: 'on-failure'
    networks:
        - network_default
    environment:
      POSTGRES_USER: telewin_user_client
      POSTGRES_PASSWORD: telewin_user_client_password
      POSTGRES_DB: telewin_app_db
    volumes:
      - PGDATA:/var/lib/postgresql/data
    profiles:
      - web-app
      - db
      - all

  redis:
    container_name: redis_con
    image: redis
    expose:
      - 6379
    networks:
      - network_default
    profiles:
      - all

#  certbot:
#    image: certbot/certbot
#    container_name: certbot_con
#    networks:
#      - network_default
#    profiles:
#      - reverse-proxy
#      - all
#    volumes:
#      - nginx_certbot_conf:/etc/letsencrypt
#      - nginx_certbot_www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 720 & wait $${!}; done;'"  # Renew certificates every 720 hours = month

networks:
    network_default:

volumes:
  PGDATA:
  app_certificates:
  nginx_certbot_conf:
  nginx_certbot_www:
  media:
  prometheus_data:
  static:
