global:
  file_watch_config:
    min_poll_frequency: 250ms
    max_poll_frequency: 250ms
server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
- url: http://loki-app:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
#- job_name: system
#  static_configs:
#  - targets:
#    - localhost
#    labels:
#      __path__: /var/log/*log
#      job: varlogs
- job_name: "docker-logs"
  static_configs:
  - targets:
    - localhost
    labels:
      job: docker-logs
      __path__: /var/lib/docker/containers/*/*log

