name: MainWorkFlow

on:
    pull_request:
        branches: [main]

jobs:
    test-and-lint:
        name: "test and lint python code"
        uses: ./.github/workflows/test_lint.yml
        secrets:
            DOCKERHUB_USER: "user"
            DOCKERHUB_PASSWORD: "PASSWORD"

