name: MainWorkFlow

on:
    pull_request:
        branches: [main]

jobs:
    build-lint-test-deploy:
        runs-on: ubuntu@22.04
        steps:
          - name: checkout
            uses: actions/checkout@v5.0.0
          - name: build image
            run:  |
              docker build -t ${{ secrets.DK_USERNAME }}/${{ secrets.DK_PASSWD }} .
              
        
        
        
